Remove-Item ENV:LIBCIFPP_DATA_DIR -ErrorAction Ignore

if ($ENV:_CONDA_SET_LIBCIFPP_DATA_DIR) {
    $ENV:LIBCIFPP_DATA_DIR = $ENV:_CONDA_SET_LIBCIFPP_DATA_DIR
    Remove-Item ENV:_CONDA_SET_LIBCIFPP_DATA_DIR -ErrorAction Ignore
}
