# Workaround for a linux/conda-build specific bug
# Refer to https://github.com/conda-forge/dssp-feedstock/issues/7
c_compiler:                # [linux or win]
  - clang                  # [linux or win]
c_compiler_version:        # [linux or win]
  - 20                     # [linux or win]
cxx_compiler:              # [linux or win]
  - clangxx                # [linux or win]
cxx_compiler_version:      # [linux or win]
  - 20                     # [linux or win]
MACOSX_DEPLOYMENT_TARGET:  # [osx and x86_64]
  - 10.15                  # [osx and x86_64]
c_stdlib_version:          # [osx and x86_64]
  - 10.15                  # [osx and x86_64]

