{% set name = "DSSP" %}
{% set version = "4.5.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PDB-REDO/{{ name|lower }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8dd92fdf2a252a170c8a811e3adb752e0f2860318ecb2b6ed5e4fd1d2b5ce5e6

build:
  number: 0
  run_exports:
    - {{ pin_subpackage(name|lower, max_pin="x") }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
  host:
    - bzip2
    - eigen
    - icu
    - libboost-python-devel >=1.86.0,<1.87.0
    - zlib

test:
  requires:
    - grep  # [unix]
  imports:
    - mkdssp  # [not win]
  commands:
    - mkdssp --version
    - mkdssp --help
  source_files:
    - test/1cbs.cif.gz

about:
  home: https://pdb-redo.eu/dssp
  doc_url: https://github.com/PDB-REDO/dssp/blob/trunk/doc/mkdssp.md
  dev_url: https://github.com/PDB-REDO/dssp
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "Application to assign secondary structure to proteins"
  description: >
    DSSP (Define Secondary Structure of Proteins) is a program that assigns
    secondary structure to proteins based on their 3D structure.

    It is widely used in structural biology and bioinformatics for analyzing protein
    structures.

extra:
  recipe-maintainers:
    - padix-key
    - mhekkel
